version: '3'

services:
  zuul-server:
    image: zuul-server:0.0.1-SNAPSHOT
    container_name: zuul-server
    depends_on:
      - keycloak
      - eureka-server
    environment:
      EUREKA_SERVER_HOST: eureka-server
      EUREKA_SERVER_PORT: 8761
      KEYCLOAK_HOST: keycloak
      KEYCLOAK_PORT: 9080
      KEYCLOAK_REALM: springcloud
      KEYCLOAK_CLIENT: api-services
    ports:
    - 8081:8081

  product-service:
    image: product-service:0.0.1-SNAPSHOT
    container_name: product-service
    depends_on:
      - eureka-server
      - elasticsearch
      - mysql
    environment:
      EUREKA_SERVER_HOST: eureka-server
      EUREKA_SERVER_PORT: 8761
      ELASTICSEARCH_HOST: elasticsearch
      ELASTICSEARCH_PORT: 9300
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASS: root
      MYSQL_DB: springcloud

  eureka-server:
    image: eureka-server:0.0.1-SNAPSHOT
    container_name: eureka-server
    ports:
      - 8761:8761

  mysql:
    image: mysql:8.0.19
    container_name: mysql
    environment:
      MYSQL_DATABASE: springcloud
      MYSQL_USER: springcloud
      MYSQL_PASSWORD: springcloud
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
      #volumes:
      # - ./data:/var/lib/mysql

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    container_name: elasticsearch
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      discovery.type: single-node
      cluster.name: elasticsearch
    # volumes:
    # - ./data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200 #http portu
      - 9300:9300 #tcp portu

  kibana:
    image: docker.elastic.co/kibana/kibana:7.5.2
    container_name: kibana
    environment:
      SERVER_NAME: localhost
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200/
    ports:
      - 5601:5601


  keycloak:
    image: jboss/keycloak:9.0.3
    container_name: keycloak
    restart: on-failure
    depends_on:
      - keycloak-postgres
    command:
      [
        '-b',
        '0.0.0.0',
        '-Djboss.socket.binding.port-offset=1000',
        '-Djava.net.preferIPv4Stack=true',
        '-Dkeycloak.profile.feature.upload_scripts=enabled',
        '-Dkeycloak.migration.action=import',
        '-Dkeycloak.migration.provider=dir',
        '-Dkeycloak.migration.dir=/tmp/keycloak-import',
        '-Dkeycloak.migration.strategy=IGNORE_EXISTING',
        '-Dkeycloak.migration.usersExportStrategy=SAME_FILE',
        '-Dkeycloak.migration.realmName=springcloud'
      ]
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: keycloak-postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: keycloak
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: keycloak
      PROXY_ADDRESS_FORWARDING: "true"
      JDBC_PARAMS: "characterEncoding=UTF-8&createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true"
    ports:
      - 9080:9080
    volumes:
    - ./keycloak:/tmp/keycloak-import

  keycloak-postgres:
    image: postgres:latest
    container_name: keycloak-postgres
    restart: on-failure
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    #volumes:
    #  - ./data/keycloak:/var/lib/postgresql/data